# Use root/example as user/password credentials
version: '3.1'

services:

  journal-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  journal-main:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - journal-db

